// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5UW_kb9RJIrUfg-PAwg5fVPeK-3CRgI',
    appId: '1:674466281188:android:7b5995d424f774a09b5ef1',
    messagingSenderId: '674466281188',
    projectId: 'job-timer-joao-pedro',
    storageBucket: 'job-timer-joao-pedro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOam_x9hZtetRDDA5BBNtJWmPfbzpySQ',
    appId: '1:674466281188:ios:b9f65a8db39d77ac9b5ef1',
    messagingSenderId: '674466281188',
    projectId: 'job-timer-joao-pedro',
    storageBucket: 'job-timer-joao-pedro.appspot.com',
    iosClientId: '674466281188-kv44bosn01eloikujbog35hb416vqjs5.apps.googleusercontent.com',
    iosBundleId: 'br.joao.pedro',
  );
}
